services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skillshare_app
    restart: unless-stopped
    ports:
      - "8111:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: skillshare_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: skillshare_mini
      MYSQL_USER: skill
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: skillshare_phpmyadmin
    restart: unless-stopped
    ports:
      - "8112:80"
    environment:
      PMA_HOST: database
      PMA_USER: root
      PMA_PASSWORD: root

volumes:
  db_data:
